artistic_techniques = [
    "oil painting",
    "watercolor painting",
    "acrylic painting",
    "pastel drawing",
    "charcoal drawing",
    "ink drawing",
    "graphite drawing",
    "collage",
    "digital painting",
    "photography",
    "textile",
    "mosaic",
    "graffiti",
]

genres = [
    "fantasy",
    "science fiction",
    "cyberpunk",
    "steampunk",
    "adventure",
    "mystery",
    "romance",
    "horror",
    "nature",
    "fairy tale",
    "post apocalyptic",
    "gothic",
    "slice of life",
]

environments = [
    "forest",
    "desert",
    "ocean",
    "cityscape",
    "mountains",
    "plains",
    "swamp",
    "cave",
    "island",
    "tundra",
    "ruins",
    "suburbs",
    "industrial area",
    "rooftops",
    "underground",
    "virtual realm",
    "floating islands",
    "space",
]
